### ISSUE TITLE
Write counter

### ISSUE THREAD

**Issue by Glama107** [giacomoferretti/nfc-srix-tools#5]
Hello, I’ve got a SRI512 tag & I want to write a new value on the counter in sector 5, I’ve see it’s possible with a write block but idk how with srix tools.
Thanks!

**Comment by giacomoferretti** [comment]
I wrote `srix-restore` to skip the first 6 blocks, because some of them are "not rewritable" (e.g. Countdown Counters [5-6]).
Also I don't have a SRI512, so I cannot properly test it. 
Can you tell me more about what do you want to do with your Block 5? Do you want to reset the OTP area?

**Comment by Glama107** [comment]
I want to update the count down counter, I know it’s possible because another repo made that and I’ve tried and It’s working well, If you can implement this it would be great

**Comment by giacomoferretti** [comment]
Yeah, no problem, it should be pretty easy to implement. In the meantime, can you send me the link for the other repo?

**Comment by Glama107** [comment]
Thank’s a lot for what you do ! https://github.com/Depau/nfc-st-srx
I’m just testing to crack my Transport ticket ;)

**Comment by giacomoferretti** [comment]
Just out of curiosity, which reader are you using?
I was thinking of writing a custom userspace driver for the ACR122U (and the PN532 in the future) so I can remove the libnfc dependency.

**Comment by doudz** [comment]
Does it mean we can fully restore a key, even the counter ?
I ask because I have a "dead" key where counter is set to 0 after trying to use "srix-reset"

**Comment by giacomoferretti** [comment]
You cannot increment the Countdown Counters on B5 and B6. The `srix-reset` tool decrement the counter (you can only do this for about 1024 times) to reset the OTP resettable bits area.

**Comment by Glama107** [comment]
I’m using an ACR122U on Kali Linux with Libnfc, it’s work very well with your script, if you have discord or anything i’m working on SRI512 Tag

**Comment by Luca-Ricci** [comment]
Hi, I'm reopening this discussion after 3 years, I hope it's not too difficult to answer me. I tried to change the count down counters without success. With the restore function I cannot modify the OTP bits (probably blocked) and therefore I cannot trigger the function that modifies sector 5 and 6 in the reset function. Despite the blocked OTP bits, the official machine that modifies this tag manages to lower the counter with each operation. Is there a way I can do the same thing too? I could manually force the parameter in otp-reset but I would like something more practical.
Thanks!

**Comment by giacomoferretti** [comment]
As I said (don't want to be rude):
> You cannot increment the Countdown Counters on B5 and B6. The srix-reset tool decrement the counter (you can only do this for about 1024 times) to reset the OTP resettable bits area.

You can check the datasheet for more information: https://www.st.com/resource/en/datasheet/st25tb04k.pdf
On page 10 there is the Memory mapping of the ST25TB04K/SRIX4K. As you can see, block 5 and 6 are "Count down counter" blocks (more info at page 13 about these blocks). You cannot increment these counters, only decrement them.

`srix-reset` only helps you "reset" the 5 resettable OTP blocks (0-4), by decrementing the block 6 and entering the "reload" state. You can only reset this area 1024 times.

> With the restore function I cannot modify the OTP bits (probably blocked) and therefore I cannot trigger the function that modifies sector 5 and 6 in the reset function.

The machine that you are talking about decrement that counter by 1 every operation you make. It never increment it.

Hope this clears up any doubts that you have. We can talk by email if you want to ask more info.

Anywas, this repo is buggy and badly written, so be careful :joy:

**Comment by Luca-Ricci** [comment]
Hi, don't worry, you didn't seem rude to me, in fact your explanation only helps me. However my problem is not directly related to what you said. Yes, I want to change the value of the counter, but I'm interested in lowering it, not raising it, which should theoretically be possible.My only problem was that with the reset function, the counter lowering only occurred if the OTP bytes had been changed.In my case it is impossible to change the OTP because as it is written in the documentation you attached, the OTP can be set to be non-editable. To solve the problem I'm trying to get my hands on your code to make it work without the need for OTP checking.  While I'm at it I also wanted to try changing a few functions

**Comment by giacomoferretti** [comment]
Which block are you trying to edit? Can you share the value of block 0xFF (system block)?

**Comment by Luca-Ricci** [comment]
my reading of the card gives the following output (I only take the part that interests me)

`[00] FF FF FF FF`
`[01] FF FF FF FF`
`[02] FF FF FF FF`
`[03] FF FF FF FF`
`[04] FF FF FF FF`
`[05] FC FF FF FF`
`[06] FF FF FF FF`
`[07] FF FF FF FF`

the system block is: FF FF FF FF with OTP_Lock_Regs all unlocked from b24 to b31.

My goal is to transform that FC into a FB and subsequently into an FA and so on. In the OTP reset command, since my blocks from 0 to 4 are all the same as FF I do not continue with the routine that updates block 6 and therefore block 5 does not change.

**Comment by giacomoferretti** [comment]
You simply can't.

> 32-bit binary counters
> The two 32-bit binary counters are located at block addresses 5 and 6. The ST25TB04K uses dedicated logic
> that only allows the update of a counter if the new value is lower than the previous one. This feature allows the
> application to count down by steps of 1 or more. The initial value in Counter 5 is FFFF FFFEh and is FFFF FFFFh
> in Counter 6. When the reached value is 0000 0000h, the counter is empty and cannot be reloaded. For each
> counter 5 and 6, the update is done by issuing the Write_block command. The Write_block command writes the
> new 32-bit value to the counter block address. Table 6 shows examples of how the counters operate.
> The counter programming cycles are protected by automated antitearing logic. This function allows the counter
> value to be protected in case of power down within the programming cycle. In case of power down, the counter
> value is not updated and the previous value continues to be stored.

Block 5 and 6 can only be decremented.

**Comment by giacomoferretti** [comment]
Just issue a `Write_block` command, `09 05 FB FF FF FF`.
